# Generated by Django 2.2.28 on 2024-02-29 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('cover', models.ImageField(blank=True, upload_to='cover_images')),
                ('genre', models.CharField(max_length=50)),
                ('blurb', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('puzzleID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(unique=True)),
                ('difficulty', models.FloatField(default=0.0)),
                ('popularity', models.FloatField(default=0.0)),
                ('isbn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookle.Book')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('scoreID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('guesses', models.IntegerField(default=10)),
                ('difficulty', models.IntegerField(default=0)),
                ('popularity', models.IntegerField(default=0)),
                ('puzzleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookle.Puzzle')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('commentID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('comment', models.CharField(max_length=300)),
                ('puzzleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookle.Puzzle')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
