# Generated by Django 2.2.28 on 2024-03-15 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('release_year', models.CharField(max_length=4)),
                ('country', models.CharField(max_length=255)),
                ('cover', models.CharField(default='', max_length=300)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('puzzleID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(unique=True)),
                ('difficulty', models.FloatField(null=True)),
                ('popularity', models.FloatField(null=True)),
                ('isbn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookle.Book')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_picture', models.ImageField(blank=True, default='profile_images/default.png', upload_to='profile_images')),
                ('bio', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('scoreID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('guesses', models.IntegerField(default=8)),
                ('difficulty', models.IntegerField(null=True)),
                ('popularity', models.IntegerField(null=True)),
                ('puzzleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookle.Puzzle')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('comment', models.CharField(max_length=300)),
                ('puzzleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookle.Puzzle')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
