# Generated by Django 2.2.28 on 2024-03-14 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookle', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Scores',
            new_name='Score',
        ),
        migrations.RemoveField(
            model_name='book',
            name='blurb',
        ),
        migrations.AddField(
            model_name='book',
            name='country',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='release_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images'),
        ),
    ]
