# Generated by Django 2.2.28 on 2024-03-15 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookle', '0002_auto_20240315_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
    ]
