# Generated by Django 2.2.28 on 2024-03-14 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookle', '0002_auto_20240229_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'UserProfile', 'verbose_name_plural': 'UserProfiles'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='blurb',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='userID',
        ),
        migrations.AddField(
            model_name='book',
            name='country',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='release_year',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, default='Write a bio! ', max_length=250),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_picture',
            field=models.ImageField(blank=True, default=None, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='Unknown', max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='date',
            field=models.DateField(default='2000-01-01', unique=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='isbn',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='bookle.Book'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='puzzleID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
