# Generated by Django 2.2.28 on 2024-03-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookle', '0003_remove_comment_parent_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
